### PR TITLE
Feature/84 profile page

### PR DESCRIPTION
**Pull request by mert-aydin**
Profile page development

### CODE REVIEW

**Review by sadikkuzu — COMMENTED** [review]
Looks cool ✨ 
Thanks

profile


But i see repetitive memories:
stories

Is it because of backend endpoint response?

**Comment by ayhncvdr2** [comment]
only happens in profile tab. maybe we can store the stories as set so that no duplicates allowed @mert-aydin

**Comment by mert-aydin** [comment]
@ayhncvdr2 @sadikkuzu my bad. I multiplied the story list to see how the screen will behave on longer lists. Fixed now.

**Review by sadikkuzu — APPROVED** [review]
Looks stunning ✨ 
Thanks 🚀

**Pull request merged**
